import "./globals.css";
import type { Metadata } from "next";
import { kausan, poppins } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${kausan.variable} ${poppins.variable}`}>
      <body>{children}</body>
    </html>
  );
}
